services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "54320:5432"
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # - type: bind
      #   source: ./pg/init.sql
      #   target: /docker-entrypoint-initdb.d/init.sql
      #   read_only: true

volumes:
  db-data:
